# Generated by Django 4.2.19 on 2025-02-12 22:26

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_mumble_quick_connect", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the section", max_length=255, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="MumbleLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the Mumble server/channel", max_length=255
                    ),
                ),
                (
                    "url",
                    models.URLField(help_text="URL to the channel", max_length=255),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mumble_links",
                        to="aa_mumble_quick_connect.section",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mumble Link",
                "verbose_name_plural": "Mumble Links",
                "default_permissions": (),
            },
        ),
    ]
