# Generated by Django 4.2.19 on 2025-02-12 23:15

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_mumble_quick_connect", "0002_section_mumblelink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mumblelink",
            name="url",
            field=models.CharField(help_text="URL to the channel", max_length=255),
        ),
    ]
