# Generated by Django 4.2.19 on 2025-02-12 23:22

# Django
from django.db import migrations, models

# AA Mumble Quick Connect
import aa_mumble_quick_connect.models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_mumble_quick_connect", "0003_alter_mumblelink_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mumblelink",
            name="url",
            field=models.CharField(
                help_text="URL to the channel",
                max_length=255,
                validators=[aa_mumble_quick_connect.models.validate_mumble_url],
            ),
        ),
    ]
