# Generated by Django 4.2.19 on 2025-02-13 11:22

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_mumble_quick_connect", "0004_alter_mumblelink_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mumblelink",
            name="name",
            field=models.CharField(
                help_text="Name of the Mumble channel", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="mumblelink",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Section the Mumble channel belongs to. (Optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mumble_links",
                to="aa_mumble_quick_connect.section",
                verbose_name="Section",
            ),
        ),
    ]
